export default [
	'tools/figma.png',
	'tools/trello.png', 
	'tools/xd.png', 
	'tools/ps.png',  
	'tools/ai.png', 
	'tools/io.png', 
	'tools/html.png', 
	'tools/css.png', 
	'tools/javascript.png', 
	'tools/bootstrap.png', 
	'tools/react.png', 
	'tools/tailwind.png', 
	'tools/vue.png', 
	'tools/node.png', 
	'tools/github.png', 
	'tools/vscode.png', 
]
